# Generated by Django 3.2.16 on 2023-06-02 17:56

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230528_0709'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('publshed_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
