# Generated by Django 3.2.16 on 2023-06-02 17:57

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('published_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
